-- mySQL 
-- Esta parte de creacion de bd y drops no las enviariamos:
      
-- CREAR BASE DE DATOS SI NO EXISTE
      
CREATE DATABASE IF NOT EXISTS UPEGaming
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE UPEGaming;

      
-- ELIMINAR TABLAS SI EXISTEN (orden inverso a dependencias)
      
DROP TABLE IF EXISTS JUEGO_IMAGEN;
DROP TABLE IF EXISTS FAQ;
DROP TABLE IF EXISTS REPORTE_COMENTARIO;
DROP TABLE IF EXISTS COMENTARIO;
DROP TABLE IF EXISTS CALIFICACION;
DROP TABLE IF EXISTS FAVORITO;
DROP TABLE IF EXISTS JUEGO_PLATAFORMA;
DROP TABLE IF EXISTS JUEGO_GENERO;
DROP TABLE IF EXISTS JUEGO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS PLATAFORMA;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS ROL_PERMISO;
DROP TABLE IF EXISTS PERMISO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;

      
-- CREACIÓN DE TABLAS
      

CREATE TABLE ROL (
  id_rol INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PERMISO (
  id_permiso INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(255)
);

CREATE TABLE ROL_PERMISO (
  id_rol INT NOT NULL,
  id_permiso INT NOT NULL,
  PRIMARY KEY (id_rol, id_permiso),
  FOREIGN KEY (id_rol) REFERENCES ROL(id_rol) ON DELETE CASCADE,
  FOREIGN KEY (id_permiso) REFERENCES PERMISO(id_permiso) ON DELETE CASCADE
);

CREATE TABLE USUARIO (
  id_usuario INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  rol_id INT NOT NULL,
  avatar VARCHAR(255) NULL,
  fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado ENUM('activo','restringido') DEFAULT 'activo',
  restriccion_hasta DATETIME DEFAULT NULL,
  FOREIGN KEY (rol_id) REFERENCES ROL(id_rol)
);

CREATE TABLE EMPRESA (
  id_empresa INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  sitio_web VARCHAR(150)
);

CREATE TABLE PLATAFORMA (
  id_plataforma INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE GENERO (
  id_genero INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE JUEGO (
  id_juego INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  descripcion TEXT,
  fecha_lanzamiento DATE,
  id_empresa INT NOT NULL,
  imagen_portada VARCHAR(255),
  FOREIGN KEY (id_empresa) REFERENCES EMPRESA(id_empresa)
);

CREATE TABLE JUEGO_GENERO (
  id_juego INT NOT NULL,
  id_genero INT NOT NULL,
  PRIMARY KEY (id_juego, id_genero),
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE,
  FOREIGN KEY (id_genero) REFERENCES GENERO(id_genero) ON DELETE CASCADE
);

CREATE TABLE JUEGO_PLATAFORMA (
  id_juego INT NOT NULL,
  id_plataforma INT NOT NULL,
  PRIMARY KEY (id_juego, id_plataforma),
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE,
  FOREIGN KEY (id_plataforma) REFERENCES PLATAFORMA(id_plataforma) ON DELETE CASCADE
);

CREATE TABLE FAVORITO (
  id_usuario INT NOT NULL,
  id_juego INT NOT NULL,
  fecha_agregado DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_usuario, id_juego),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE
);

CREATE TABLE CALIFICACION (
  id_usuario INT NOT NULL,
  id_juego INT NOT NULL,
  puntuacion TINYINT NOT NULL CHECK (puntuacion BETWEEN 0 AND 5),
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_usuario, id_juego),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE
);

CREATE TABLE COMENTARIO (
  id_comentario INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT NOT NULL,
  id_juego INT NOT NULL,
  contenido TEXT NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado ENUM('activo','reportado','eliminado') DEFAULT 'activo',
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE
);

CREATE TABLE REPORTE_COMENTARIO (
  id_reporte INT AUTO_INCREMENT PRIMARY KEY,
  id_comentario INT NOT NULL,
  id_usuario_reporta INT NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  fecha_reporte DATETIME DEFAULT CURRENT_TIMESTAMP,
  id_moderador_accion INT NULL,
  fecha_accion DATETIME NULL,
  accion ENUM('ignorar','restringir') DEFAULT NULL,
  observaciones VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (id_comentario) REFERENCES COMENTARIO(id_comentario) ON DELETE CASCADE,
  FOREIGN KEY (id_usuario_reporta) REFERENCES USUARIO(id_usuario),
  FOREIGN KEY (id_moderador_accion) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE FAQ (
  id_faq INT AUTO_INCREMENT PRIMARY KEY,
  pregunta VARCHAR(255) NOT NULL,
  respuesta TEXT,
  visible BOOLEAN DEFAULT TRUE,
  id_autor INT NOT NULL,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_autor) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE JUEGO_IMAGEN (
  id_imagen INT AUTO_INCREMENT PRIMARY KEY,
  id_juego INT NOT NULL,
  url_imagen VARCHAR(255) NOT NULL,
  FOREIGN KEY (id_juego) REFERENCES JUEGO(id_juego) ON DELETE CASCADE
);
