-- esto no lo enviaremos:

-- CREAR BASE DE DATOS SI NO EXISTE
      
CREATE DATABASE IF NOT EXISTS UPEGaming
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE UPEGaming;
      
-- Inicializar en orden
      
SET FOREIGN_KEY_CHECKS = 0;

-- Eliminar vistas
DROP VIEW IF EXISTS V_GENEROS_TOP2_USUARIO;

-- Eliminar triggers
DROP TRIGGER IF EXISTS trg_notificar_publicacion;

-- Eliminar eventos
DROP EVENT IF EXISTS evento_actualizar_restricciones;

-- Eliminar tablas
DROP TABLE IF EXISTS JUEGO_IMAGEN;
DROP TABLE IF EXISTS REPORTE_COMENTARIO;
DROP TABLE IF EXISTS COMENTARIO;
DROP TABLE IF EXISTS CALIFICACION;
DROP TABLE IF EXISTS FAVORITO;
DROP TABLE IF EXISTS JUEGO_PLATAFORMA;
DROP TABLE IF EXISTS JUEGO_GENERO;
DROP TABLE IF EXISTS ENVIO_NOTIFICACION;
DROP TABLE IF EXISTS RESTRICCION_USUARIO;
DROP TABLE IF EXISTS FAQ;
DROP TABLE IF EXISTS JUEGO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS PLATAFORMA;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS ROL_PERMISO;
DROP TABLE IF EXISTS PERMISO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;

SET FOREIGN_KEY_CHECKS = 1;

